import React from 'react';
import { createRoot } from 'react-dom/client';
import { App } from './App';
import { AppUpdates } from './AppUpdates';
import { initialise } from './data';
import { installNotificationNavigation } from './notificationNavigation';
import './style.css';
import './styles.css';
installNotificationNavigation();
createRoot(document.getElementById('root')!).render(<AppUpdates><App/></AppUpdates>);
void initialise();
