import {useRef,useState,type PointerEvent,type ReactNode} from 'react';
/** The same gesture as Conversations: vertical scrolling and cancelled gestures never act. */
export function SwipeRow({children,left,right,busy=false,disabled=false,className='',...props}:{children:ReactNode;left:{label:string;icon:ReactNode;run():void};right?:{label:string;icon:ReactNode;run():void};busy?:boolean;disabled?:boolean;className?:string;'data-conversation-key'?:string}){
 const [offset,setOffset]=useState(0),gesture=useRef<{id:number;x:number;y:number;dx:number;horizontal:boolean;threshold:number;blocked:boolean}|null>(null),suppress=useRef(0);
 // Recognise drags while unavailable too, so their final click cannot open the row.
 function down(e:PointerEvent<HTMLDivElement>){if(!e.isPrimary||e.button!==0)return;gesture.current={id:e.pointerId,x:e.clientX,y:e.clientY,dx:0,horizontal:false,threshold:Math.min(90,e.currentTarget.clientWidth*.25),blocked:busy||disabled};}
 function move(e:PointerEvent<HTMLDivElement>){const g=gesture.current;if(!g||g.id!==e.pointerId)return;const dx=e.clientX-g.x,dy=e.clientY-g.y;if(!g.horizontal){if(Math.abs(dy)>12&&Math.abs(dy)>=Math.abs(dx)){gesture.current=null;return;}if(Math.abs(dx)<12||Math.abs(dx)<Math.abs(dy)*1.4)return;g.horizontal=true;e.currentTarget.setPointerCapture(e.pointerId);}if(e.cancelable)e.preventDefault();g.dx=dx;setOffset(g.blocked||busy||disabled?0:Math.max(-130,Math.min(right?130:24,dx)));}
 function finish(e:PointerEvent<HTMLDivElement>,cancelled=false){const g=gesture.current;if(!g||g.id!==e.pointerId)return;gesture.current=null;setOffset(0);if(g.horizontal)suppress.current=Date.now()+600;if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);if(!cancelled&&!g.blocked&&!busy&&!disabled&&g.horizontal&&Math.abs(g.dx)>=g.threshold){if(g.dx<0)left.run();else right?.run();}}
 const action=offset>0&&right?right:left;
 return <div {...props} className={`conversation-item ${className}`} aria-busy={busy} onPointerDown={down} onPointerMove={move} onPointerUp={e=>finish(e)} onPointerCancel={e=>finish(e,true)} onLostPointerCapture={e=>{if(e.target===e.currentTarget)finish(e,true);}} onClickCapture={e=>{if(e.detail!==0&&Date.now()<suppress.current){e.preventDefault();e.stopPropagation();}}}>
 <div className={`conversation-swipe-action ${offset>0?'to-task':'to-hide'}`} aria-hidden="true">{action.icon}{action.label}</div><div className={`conversation-item-content ${offset?'swiping':''}`} style={{transform:`translateX(${offset}px)`}}>{children}</div><button className="swipe-keyboard-action" disabled={busy||disabled} onClick={left.run}>{left.label}</button></div>;
}
